# Generated by Django 5.2.8 on 2025-12-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='mark_obtained',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
