# Generated by Django 5.2.8 on 2025-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_alter_exam_mark_obtained_alter_exam_total_marks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='exam',
            name='class_number',
            field=models.IntegerField(default=1),
        ),
    ]
