# Generated by Django 5.2.8 on 2025-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_exam_options_exam_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='group_id',
            field=models.CharField(blank=True, help_text='Groups multiple student results for the same exam', max_length=100, null=True),
        ),
    ]
