# Generated by Django 5.2.8 on 2025-12-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_exam_group_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifetimepoints',
            options={'verbose_name': 'Lifetime Points', 'verbose_name_plural': 'Lifetime Points'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='group_id',
            field=models.CharField(blank=True, help_text='Groups multiple student results for the same exam (bulk entry)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lifetimepoints',
            name='points_earned',
            field=models.IntegerField(default=0, help_text='Total points earned from exams'),
        ),
        migrations.AlterField(
            model_name='lifetimepoints',
            name='points_spent',
            field=models.IntegerField(default=0, help_text='Points spent on rewards'),
        ),
        migrations.CreateModel(
            name='PointsSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField(help_text='Number of points spent')),
                ('description', models.CharField(help_text='How points were used', max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.student')),
            ],
            options={
                'verbose_name': 'Points Spent',
                'verbose_name_plural': 'Points Spent',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
