# Generated by Django 5.2.8 on 2025-12-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_alter_lifetimepoints_options_alter_exam_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_id',
            field=models.IntegerField(blank=True, help_text='Unique exam identifier (same for bulk entries)', null=True),
        ),
    ]
