# Generated by Django 5.2.8 on 2025-12-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_exam_exam_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradescale',
            options={'ordering': ['grade_name']},
        ),
        migrations.RemoveField(
            model_name='gradescale',
            name='min_percentage',
        ),
        migrations.RemoveField(
            model_name='gradescale',
            name='max_percentage',
        ),
    ]
