# Generated by Django 5.2.8 on 2026-01-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0007_remove_unused_percentage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_pdf',
            field=models.FileField(blank=True, help_text='PDF file containing exam questions', null=True, upload_to='exam_questions/'),
        ),
    ]
