# Generated by Django 5.2.8 on 2026-01-13 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0009_studentprofile_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher who created this exam', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examtype',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher who owns this exam type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointsspent',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher who recorded this points spent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_spent_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher who owns this student', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher who owns this subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
