# Generated by Django 5.2.8 on 2026-01-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_exam_teacher_examtype_teacher_pointsspent_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsspent',
            name='date',
            field=models.DateField(),
        ),
    ]
