# Generated by Django 5.2.8 on 2026-01-18 18:45

import marks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0011_alter_pointsspent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name/abbreviation (max 10 characters)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_pdf',
            field=models.FileField(blank=True, help_text='PDF file containing exam questions', null=True, upload_to=marks.models.Exam.exam_pdf_folder_path),
        ),
    ]
