# Generated by Django 5.2.8 on 2026-01-18 19:48

from django.db import migrations, models


def split_student_names(apps, schema_editor):
    """Split existing student names into first_name and last_name"""
    Student = apps.get_model('marks', 'Student')

    for student in Student.objects.all():
        if student.name:
            name_parts = student.name.strip().split(' ', 1)
            student.first_name = name_parts[0][:10]  # Limit to 10 chars
            if len(name_parts) > 1:
                student.last_name = name_parts[1][:10]  # Limit to 10 chars
            else:
                student.last_name = None
            student.save()


def reverse_split_student_names(apps, schema_editor):
    """Reverse the name splitting for migration rollback"""
    Student = apps.get_model('marks', 'Student')

    for student in Student.objects.all():
        if student.last_name:
            student.name = f"{student.first_name} {student.last_name}"
        else:
            student.name = student.first_name
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0012_subject_short_name_alter_exam_question_pdf'),
    ]

    operations = [
        # Add new fields
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', help_text='First name (max 10 characters)', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name (max 10 characters)', max_length=10, null=True),
        ),

        # Data migration to split names
        migrations.RunPython(
            split_student_names,
            reverse_code=reverse_split_student_names
        ),

        # Remove old field
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
