# Generated by Django 5.2.8 on 2026-01-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0013_split_student_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for the uploaded PDF file', max_length=255, null=True),
        ),
    ]
