# Generated by Django 5.2.8 on 2026-01-22 14:19

import marks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0014_exam_cloudinary_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marked_answer_paper',
            field=models.FileField(blank=True, help_text='Marked/examined answer paper (PDF/ZIP/RAR, max 10MB)', null=True, upload_to=marks.models.Exam.marked_answer_folder_path),
        ),
    ]
