# Generated by Django 5.2.8 on 2026-01-23 04:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0015_add_marked_answer_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='marked_answer_paper',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Marked/examined answer paper (PDF/ZIP/RAR, max 10MB)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='PDF file containing exam questions', max_length=255, null=True),
        ),
    ]
