# Generated by Django 5.2.8 on 2026-01-23 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0016_switch_to_cloudinary_fields_with_custom_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='cloudinary_public_id',
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('spent', 'Points Spent (Manual)'), ('exam_bonus', 'Exam Performance Bonus'), ('exam_penalty', 'Exam Performance Penalty'), ('monthly_win', 'Monthly Winner Bonus')], default='spent', help_text='Type of point transaction', max_length=20)),
                ('points_change', models.IntegerField(help_text='Points gained (positive) or lost (negative). Use negative values for spending/penalties.')),
                ('description', models.CharField(help_text='Description of the transaction', max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, help_text='Related exam (for exam-based transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marks.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.student')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher who recorded this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
