# Generated by Django 5.2.8 on 2026-01-23 05:59

from django.db import migrations


def migrate_points_spent_to_transactions(apps, schema_editor):
    """Migrate existing PointsSpent records to PointTransaction records"""
    PointsSpent = apps.get_model('marks', 'PointsSpent')
    PointTransaction = apps.get_model('marks', 'PointTransaction')

    # Get all existing PointsSpent records
    for points_spent in PointsSpent.objects.all():
        # Create corresponding PointTransaction record
        PointTransaction.objects.get_or_create(
            student=points_spent.student,
            teacher=points_spent.teacher,
            transaction_type='spent',
            date=points_spent.date,
            description=points_spent.description,
            defaults={
                'points_change': -points_spent.points_spent,  # Negative for spending
                'exam': None
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0017_add_point_transaction_model'),
    ]

    operations = [
        migrations.RunPython(migrate_points_spent_to_transactions),
    ]
