# Generated by Django 5.2.8 on 2026-02-06 15:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0019_examquestionpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Legacy field - question papers now stored in ExamQuestionPaper model', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examquestionpaper',
            name='question_pdf',
            field=cloudinary.models.CloudinaryField(help_text='PDF file containing exam questions', max_length=255),
        ),
    ]
