# Generated by Django 5.2.8 on 2026-02-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0020_alter_exam_question_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='raw_password',
            field=models.CharField(blank=True, help_text='Plain-text password for teacher reference', max_length=128, null=True),
        ),
    ]
