# Generated by Django 5.2.8 on 2026-02-09 05:32

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0021_add_raw_password_to_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenterExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_display_id', models.CharField(help_text='Exam identifier displayed to students', max_length=50)),
                ('class_number', models.IntegerField(help_text='Class number (1-12)')),
                ('subject', models.CharField(help_text='Subject name', max_length=200)),
                ('exam_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], help_text='Online or Offline exam', max_length=10)),
                ('exam_type', models.CharField(choices=[('cq', 'CQ'), ('mcq', 'MCQ')], help_text='CQ or MCQ', max_length=5)),
                ('total_marks', models.PositiveIntegerField(help_text='Total marks for the exam')),
                ('exam_date', models.DateField(help_text='Date of the exam')),
                ('start_time', models.TimeField(help_text='Start time of the exam')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Exam duration in minutes')),
                ('submission_duration_minutes', models.PositiveIntegerField(default=10, help_text='Answer submission window in minutes (online exams only)')),
                ('question_pdf', cloudinary.models.CloudinaryField(blank=True, help_text='Question paper PDF (mandatory for online exams, max 1 MB)', max_length=255, null=True)),
                ('bonus_time_minutes', models.PositiveIntegerField(default=0, help_text='Bonus time granted by teacher (extends submission for online, extends exam for offline)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Teacher who created this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_center_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Center Exam',
                'verbose_name_plural': 'Exam Center Exams',
                'ordering': ['-exam_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', cloudinary.models.CloudinaryField(help_text='Answer sheet (PDF / ZIP / RAR, max 10 MB)', max_length=255)),
                ('is_final', models.BooleanField(default=True, help_text='Whether this is the final (latest) submission')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_center_submissions', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='marks.examcenterexam')),
            ],
            options={
                'verbose_name': 'Answer Submission',
                'verbose_name_plural': 'Answer Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
