# Generated by Django 5.2.8 on 2026-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0022_examcenterexam_answersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcenterexam',
            name='exam_bonus_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Bonus time added to exam duration (granted while running)'),
        ),
        migrations.AddField(
            model_name='examcenterexam',
            name='submission_bonus_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Bonus time added to submission window (granted during submission)'),
        ),
        migrations.AlterField(
            model_name='examcenterexam',
            name='bonus_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Legacy bonus time field (deprecated, kept for migration compatibility)'),
        ),
    ]
