# Generated by Django 5.2.8 on 2026-02-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0023_split_bonus_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcenterexam',
            name='chapter',
            field=models.CharField(blank=True, default='', help_text='Chapter number or name', max_length=100),
        ),
    ]
