# Generated by Django 5.2.8 on 2026-02-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0024_add_chapter_to_examcenterexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcenterexam',
            name='chapter',
            field=models.CharField(blank=True, default='', help_text='Chapter number or name (max 10 chars)', max_length=10),
        ),
    ]
