# Generated by Django 5.2.8 on 2026-02-15 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0026_add_push_subscription_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder_5min', '5-minute reminder before exam'), ('reminder_start', 'Exam has started'), ('reminder_3min_end', '3-minute warning before exam ends'), ('exam_ended', 'Exam has ended / submission open'), ('submission_3min', '3-minute warning before submission closes')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='marks.examcenterexam')),
            ],
            options={
                'verbose_name': 'Exam Notification Log',
                'verbose_name_plural': 'Exam Notification Logs',
                'unique_together': {('exam', 'notification_type')},
            },
        ),
    ]
