# Generated by Django 5.2.8 on 2026-03-13 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0027_add_exam_notification_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestTeacherAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_teacher_account', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest Teacher Account',
                'verbose_name_plural': 'Guest Teacher Accounts',
            },
        ),
    ]
