# Generated by Django 5.2.8 on 2026-08-11 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0031_guestteacheraccount_is_publicly_accessible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('slug_number', models.PositiveIntegerField(help_text='Immutable per-teacher workspace number (1, 2, 3...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Teacher who owns this workspace', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'ordering': ['slug_number'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this exam belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='marks.workspace'),
        ),
        migrations.AddField(
            model_name='examcenterexam',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this exam belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_center_exams', to='marks.workspace'),
        ),
        migrations.AddField(
            model_name='examquestionpaper',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this question paper belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_papers', to='marks.workspace'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this exam type belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='marks.workspace'),
        ),
        migrations.AddField(
            model_name='guestteacheraccount',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this guest is pinned to (null = all active)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_accounts', to='marks.workspace'),
        ),
        migrations.AddField(
            model_name='pointsspent',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this points-spent entry belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_spent_records', to='marks.workspace'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this point transaction belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='marks.workspace'),
        ),
        migrations.AddField(
            model_name='student',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this student belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='marks.workspace'),
        ),
        migrations.AddField(
            model_name='subject',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this subject belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='marks.workspace'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('teacher', 'slug_number'), name='unique_workspace_slug_per_teacher'),
        ),
    ]
