# Generated by Django 5.2.8 on 2026-08-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0035_workspace_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('reminder_5min', '5-minute reminder before exam'), ('reminder_start', 'Exam has started'), ('reminder_3min_end', '3-minute warning before exam ends'), ('exam_ended', 'Exam has ended / submission open'), ('teacher_exam_started', 'Teacher notified: exam started'), ('teacher_exam_ended', 'Teacher notified: exam ended'), ('teacher_submission_ended', 'Teacher notified: submission ended')], max_length=30),
        ),
    ]
